#Server config
spring.application.name=producer-app
server.port=8081

#Kafka config
spring.kafka.bootstrap-servers=kafka:9092
#spring.kafka.bootstrap-servers=${BOOTSTRAP_HOST:kafka}:9092          // For local development/testing/debugging
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#Optional topic config
#app.kafka.topic=orders




